main.py
import os
import logging
from routes.discovery import discovery
from routes.enhancement import enhancement
from flask import Flask, request, render_template


logger = logging.getLogger(__name__)
app = Flask(__name__)

app.register_blueprint(discovery)
app.register_blueprint(enhancement)

app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 1  # disable caching
app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'
app.config['SECRET_KEY'] = os.urandom(24)


@app.route('/', methods=['GET'])
def init():
    return render_template('home.html')


@app.errorhandler(404)
def page_not_found(e):
    return render_template('error_404.html')

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=3000, debug=True)

routes/discovery.py
import os

from flask import render_template, request, session, Blueprint
from src.xes_handler import csv_to_xes
from src.utils import xes_to_df, get_file_path, create_performance_dfg, create_generalized_dfg, store_filtered_log
import src.const as cn

discovery = Blueprint('discovery', __name__)

files_dict = {}
resources_list = []

data_dict = {}
file_name = None

gui_interface = 'discovery.html'
ROOT_DIR = os.path.abspath(os.curdir)


@discovery.route('/discovery', methods=['GET', 'POST'])
def init():
    # Initialize session and page
    if request.method == 'GET':
        session[cn.FILE_LIST] = data_dict
        session[cn.MEASURES] = {cn.ALL: {}}
        session[cn.RESP] = ''
        
        return render_template(gui_interface)

    if request.method == 'POST':
        file_name = request.form.get(cn.FILE)
        # handle DELETE request
        if request.form.get('delete_file') == 'true':
            session['plot_file'] = {}
            if file_name in data_dict:
                data_dict.pop(file_name)
                
            if cn.RESP in session:
                session[cn.RESP] = ''
            if session.get(cn.FILE) == file_name:
                session[cn.FILE] = ''
        else: # handle file change request
            session[cn.FILE] = file_name

        session[cn.FILE_LIST] = data_dict
        
        return render_template(gui_interface)



@discovery.route('/csv-processing', methods=['POST'])
def csv_processing():
    if 'csv-file' not in request.files:
        return render_template(gui_interface)
    
    file = request.files['csv-file']
    if file.filename == '':
        return render_template(gui_interface)
    if file:
        if file.filename.endswith('csv'):
            file_path = os.path.join(ROOT_DIR, 'docs', 'logs', 'csv', file.filename)
            file.save(file_path)
            dest_name = csv_to_xes(file_path)
        return render_template(gui_interface, message = "Saved as: {dest_name}", dest_name = dest_name)
    


@discovery.route('/select-logs', methods=['POST'])
def choose_path():
    f = request.files.get('file')
    
    if f.filename.endswith('xes'):
        file_path = os.path.join(ROOT_DIR, 'docs', 'logs', f.filename)
        f.save(file_path)
        session['fdata'] = {}
        session[cn.FILE] = f.filename
        data_dict[f.filename] = file_path
        session[cn.FILE_LIST] = data_dict
        
        df = xes_to_df(file_path)

        resources_list = []
        cases_list = []

        if cn.RESOURCE in df.keys():
            resources = df[cn.RESOURCE].unique()
            resources_list = list(resources.tolist())

        if cn.CASE in df.keys():
            cases = df[cn.CASE].unique()
            cases_list = list(cases.tolist())

        session['fdata'] = { 
                'filters':{
                'resources': resources_list, 'cases': cases_list}
            }
                           
    return render_template(gui_interface)

@discovery.route('/filter-file', methods=['GET'])
def filter_file():
    if request.method == 'GET':
        file_name = request.args.get(cn.FILE)
        file_path = get_file_path(file_name)
        session[cn.PATH] = file_path
        res_opt = request.args.get('resource_option')
        case_opt = request.args.get('case_option')
        
        if (res_opt == 'none' and case_opt == 'none'):
            filtering_conditions = {}
        else:
            session[cn.FILE_LIST][cn.FILTERS] = {}
            filtering_conditions = {}
            if res_opt != 'none':
                filtering_conditions[cn.RESOURCE] = res_opt
                session['resource_opt'] = res_opt
            if case_opt != 'none':
                selected_case = int(case_opt)
                filtering_conditions[cn.CASE] = selected_case
                session['case_opt'] = int(case_opt)

            outfile = store_filtered_log(file_path, filtering_conditions)
            
            file_name = os.path.basename(outfile)
            
            data_dict[file_name] = outfile
            session[cn.FILE_LIST] = data_dict
            
        print(session[cn.FILE_LIST])

        return render_template(gui_interface)

@discovery.route('/discover-activity', methods=['GET', 'POST'])
def discover_dfg():    
    
    if request.method == 'POST':
        file_name = request.form[cn.FILE]
        file_path = session[cn.FILE_LIST][file_name]
        session[cn.PATH] = file_path
        (nodes, edges) = create_generalized_dfg(file_path)
        session[cn.RESP] = {'nodes': nodes, 'edges': edges}

        session['plot_file'] = {}
        return render_template(gui_interface, button_pressed='btn1')


@discovery.route('/discover-performance', methods=['POST'])
def discover_performance():    
    if request.method == 'POST':
        file_name = request.form[cn.FILE]
        file_path = session[cn.FILE_LIST][file_name]
        session[cn.PATH] = file_path
        (nodes, edges) = create_generalized_dfg(file_path, is_performance=True)
        session[cn.RESP] = {'nodes': nodes, 'edges': edges}

        session['plot_file'] = {}
        return render_template(gui_interface, button_pressed='btn2')

routes/enhancement.py
import os

from flask import render_template, request, session, Blueprint

from src.utils import *
from src.plot_creation import *
import src.const as cn

enhancement = Blueprint('enhancement', __name__)

gui_interface = 'enhancement.html'
ROOT_DIR = os.path.abspath(os.curdir)

@enhancement.route('/measurements_gui')
def measurements_gui():
    return render_template(gui_interface)


@enhancement.route('/measurements_gui/measure', methods=['GET'])
def get_global_plot():
    file_path = session[cn.PATH]
    args_keys = request.args.keys()
    for key in args_keys:
        if key == 'graph':
            if request.args[key] == cn.PERFORMANCE: # reconstruct the frequency DFG
                (nodes, edges) = create_performance_dfg(file_path)
                session[cn.RESP] = {'nodes': nodes, 'edges': edges}
            elif request.args[key] == cn.FREQUENCY: # reconstruct the performance DFG
                (nodes, edges) = create_dfg(file_path)
                session[cn.RESP] = {'nodes': nodes, 'edges': edges}
        else: # Create measures plot
            df = xes_to_df(file_path)
                
            fig_path = get_plot(key, df)
            session[cn.MEASURES][cn.ALL][key] = fig_path
    return render_template(gui_interface)


@enhancement.route('/view/activity', methods=['GET'])
def see_plot():
    args = request.args
    activity_name = args.get('activity_id')
    file_name = session[cn.FILE]
    file_path = get_file_path(file_name)
    session['current_activity'] = activity_name
    # space plot generation
    if args.get(cn.SPACE):
        fig_path = get_space_plot(activity_name, file_path)       
        if not cn.MEASURES in session.keys():
            session[cn.MEASURES] = {activity_name: {cn.SPACE: fig_path}}
        elif not activity_name in session[cn.MEASURES].keys():
            session[cn.MEASURES][activity_name] = {cn.SPACE: fig_path}
        else:
            session[cn.MEASURES][activity_name][cn.SPACE] = fig_path
    
    return render_template(gui_interface)

templates/discovery.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% extends 'base.html' %}

    {% block head %}
    {{ super() }}
    <title>RoboTrace | Discovery </title>

    <style>
        .btn-nav {
            font-size: 0.9rem;
        }

        .offcanvas-header {
            background-color: #f8f9fa;
        }

        .btn-outline-secondary {
            border-color: #6c757d;
        }

        .table th,
        .table td {
            vertical-align: middle;
        }

        .container-fluid {
            max-width: 1400px;
        }
    </style>
    {% endblock %}
</head>
{% block content %}

<body>


    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
        <div class="container-fluid">
            <a class="navbar-brand" style="font-size: 1.5rem;" href="/">RoboTrace-discovery</a>
        </div>
    </nav>

    <!-- Sidebar -->
    <div class="d-flex flex-column flex-lg-row">
        <div class="sidebar">
            <nav class="navbar navbar-dark">
                <p class="navbar-brand">Start...</p>
                <div class="nav flex-column">
                    <button class="btn btn-outline-secondary btn-nav" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseInput" aria-expanded="false" aria-controls="collapseInput">
                        <i class="fa fa-table" aria-hidden="true"></i> Toggle File Upload
                    </button>
                </div>

                {% if session.files %}
                {% set files = session.files %}
                <p class="navbar-brand">Available Files</p>

                <form id="filters" action="{{ url_for('discovery.init') }}" method="POST">
                    {% for f in files %}
                    <button class="btn btn-outline-secondary btn-nav" type="submit" name="file_name" value="{{ f }}"
                        title="{{ f }}">
                        {{ f }}
                    </button>
                    {% endfor %}
                </form>


                {% endif %}

            </nav>
        </div>
    </div>

    <div class="content">
    <div class="offcanvas offcanvas-start" id="filter-tab">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title">Event log: {{ session.file_name }}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
        </div>
        <div class="offcanvas-body">
            {% if session.fdata %}
            <div class="card">
                <div class="card-header">
                    <h4>Filtering</h4>
                </div>
                <div class="card-body">
                    {% set filter = session.fdata.filters %}
                    <form id="filters" action="{{url_for('discovery.filter_file')}}" method="GET">
                        {% if filter.resources %}
                        <div class="mb-3">
                            <label for="selectRes" class="form-label">
                                <h5>Resources</h5>
                            </label>
                            <select class="form-select" name="resource_option" id="selectRes">
                                <option value="none" selected>None</option>
                                {% for resource in filter.resources %}
                                <option value="{{resource}}" {% if resource_opt==resource %} selected {% endif %}>{{
                                    resource }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        {% endif %}
                        {% if filter.cases %}
                        <div class="mb-3">
                            <label for="selectCase" class="form-label">
                                <h5>Cases</h5>
                            </label>
                            <select class="form-select" name="case_option" id="selectCase">
                                <option value="none" selected>None</option>
                                {% for case in filter.cases %}
                                <option value="{{case}}" {% if case_opt==case %} selected {% endif %}>{{ case }}
                                </option>
                                {% endfor %}
                            </select>
                            <input type="hidden" name="file_name" value="{{session.file_name}}" />
                        </div>
                        {% endif %}
                        <button type="submit" class="btn btn-outline-secondary" title="Log Filtering">Filter!</button>
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="container-fluid mt-3">
        <div class="collapse" id="collapseInput">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8 mb-4">
                    <div class="card shadow-sm">
                        <div class="card-header bg-tale text-white">
                            <h5 class="mb-0">Upload</h5>
                        </div>
                        <div class="card-body text-center">
                            <p class="mb-3"> Upload Event Log</p>
                            <form action="select-logs" method="POST" enctype="multipart/form-data">
                                <label hidden for="file" class="form-label">Choose File</label>
                                <div class="input-group">
                                    <input class="form-control" type="file" name="file" id="file" />
                                    <button class="btn btn-tale" type="submit">Upload</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-8 mb-4">
                    <div class="card shadow-sm">
                        <div class="card-header bg-csv text-white">
                            <h5 class="mb-0">Parse</h5>
                        </div>
                        <div class="card-body text-center">
                            <p class="mb-3"><strong>OR</strong> use the CSV Parser</p>
                            <button class="btn btn-csv w-100" id="uploadBtn">CSV Parser</button>
                            <div id="uploadDialog" class="mt-3" style="display: none;">
                                <form action="{{ url_for('discovery.csv_processing') }}" method="POST"
                                    enctype="multipart/form-data">
                                    <label hidden for="csv-file" class="form-label">Upload CSV File</label>
                                    <div class="input-group">
                                        <input class="form-control" type="file" name="csv-file" id="csv-file">
                                        <button type="submit" class="btn btn-csv">Parse</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    {% if session.file_name %}
    <div class="container-fluid mt-3">
        <div class="card shadow-sm p-4">
            <table class="table text-center">
                <thead>
                    <tr>
                        <th scope="col">Event Log</th>
                        <th scope="col">Actions</th>
                        <th scope="col">Analysis</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% set value = session.file_name %}
                    <tr id="{{ value }}">
                        <td>{{ value }}</td>
                        <td>
                            <button class="btn btn-outline-dark" type="button" data-bs-toggle="offcanvas"
                                data-bs-target="#filter-tab"><i class="fa fa-filter" aria-hidden="true"></i> Filter
                                Log</button>
                        </td>
                        <td>
                            <div style="display: flex; justify-content: center; align-items: center; gap: 10px;">
                                <form action="{{ url_for('discovery.discover_dfg') }}" method="POST">
                                    <input type="hidden" name="file_name" value="{{value}}" />
                                    <button class="btn btn-outline-dark" type="submit">Discover Process</button>
                                </form>
                                <button class="btn btn-outline-dark" title="Please Discover Process" type="button"
                                    onclick="openNewTab()" id="enhancement_gui" disabled>Enhancement GUI</button>
                                <script>
                                    function openNewTab() {
                                        localStorage.setItem('sharedContent', document.getElementById('graph-container').innerHTML);
                                        window.open("{{ url_for('enhancement.measurements_gui') }}", "_blank");
                                    }
                                </script>
                            </div>
                        </td>
                        <td>
                            <form action="{{ url_for('discovery.init') }}" method="POST">
                                <input type="hidden" name="delete_file" value="true">
                                <input type="hidden" name="file_name" value="{{value}}" />
                                <button type="submit" class="btn btn-outline-danger" title="Delete Log"><i
                                        class="fa fa-close"></i></button>
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    {% endif %}


    {% if session['response_data'] != "" %}
    <div class="container-fluid mt-4">
        <div class="card shadow-sm p-4 mb-4" id="graph-container"
            style="background-color: #f8f9fa; border-radius: 8px;">
            <div class="d-flex justify-content-between mb-3">
                <div class="d-flex gap-2">
                    <form action="{{ url_for('discovery.discover_dfg') }}" method="POST">
                        <input type="hidden" name="file_name" value="{{value}}" />
                        <button class="btn btn-outline-dark {% if button_pressed == 'btn1' %}btn-purple{% endif %}"
                            type="submit" id="btn1">Frequency Graph</button>
                    </form>
                    <form action="{{ url_for('discovery.discover_performance') }}" method="POST">
                        <input type="hidden" name="file_name" value="{{value}}" />
                        <button class="btn btn-outline-dark {% if button_pressed == 'btn2' %}btn-purple{% endif %}"
                            type="submit" id="btn2">Performance Graph</button>
                    </form>
                </div>

                <div class="d-flex gap-2">
                    <button id="toggle-button" class="btn btn-outline-secondary" title="Change Graph Direction">
                        <i class="fa fa-repeat" aria-hidden="true"></i> Toggle Direction
                    </button>
                    <button onclick="downloadGraph()" class="btn btn-outline-secondary" title="Download SVG">
                        <i class="fa fa-download" aria-hidden="true"></i> Download SVG
                    </button>
                </div>
            </div>

        </div>
    </div>
    {% endif %}



    <div hidden class="row card-columns">
        <div class="card">
            <script>
                const response_data = {{ session.response_data|default ("") | tojson }}
                generate_dagre(response_data)
                console.log('rd', response_data)
                if (response_data == '') {
                    document.getElementById('enhancement_gui').disabled = true;
                } else {
                    document.getElementById('enhancement_gui').disabled = false;
                    document.getElementById('enhancement_gui').title = "Open Multi-Perspective Interface"
                }
            </script>
        </div>
    </div>

</div>
    <script>
        document.getElementById('uploadBtn').addEventListener('click', function () {
            this.style.display = 'none';
            document.getElementById('uploadDialog').style.display = 'block';
        });
    </script>
</body>

{% endblock %}

</html>

templates/enhancement.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% extends 'base.html' %}

    {% block head %}
    {{ super() }}
    <title>RoboTrace | Enhancement </title>

    <script type="text/javascript" src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
    <script src='https://cdn.plot.ly/plotly-2.9.0.min.js'></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/plots.js') }}"></script>

    {% endblock %}

</head>
{% block content %}

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
        <div class="container-fluid">
            <a class="navbar-brand" style="font-size: 1.5rem;" href="/">RoboTrace-enhancement</a>
        </div>
    </nav>

    <!-- Sidebar -->
    <div class="d-flex flex-column flex-lg-row">
        <div class="sidebar">
            <nav class="navbar navbar-dark">
                <form action="{{ url_for('enhancement.get_global_plot') }}" method="GET">


                    <div class="nav flex-column">
                        <p class="navbar-brand">DFG</p>
                    
                        <input type="radio" class="btn-check" id="btn-check-frequency" name="graph" value="frequency">
                        <label class="nav-link btn btn-outline-light" for="btn-check-frequency">
                            <i class="fa fa-bars" title="See Frequency Graph"></i> Frequency
                        </label>
                    
                        <input type="radio" class="btn-check" id="btn-check-performance" name="graph" value="performance">
                        <label class="nav-link btn btn-outline-light" for="btn-check-performance">
                            <i class="fa fa-clock" title="See Performance Graph"></i> Performance
                        </label>
                    </div>
                    
                    

                    <div class="nav flex-column">
                        <p class="navbar-brand">Perspectives</p>

                        <input type="checkbox" class="btn-check" id="btn-check-space" name="space" value="1">
                        <label class="nav-link btn btn-outline-light" for="btn-check-space">
                            <i class="fa fa-map" title="See Space Plot"></i> Space
                        </label>
                        <input type="checkbox" class="btn-check" id="btn-check-battery" name="battery" value="1">
                        <label class="nav-link btn btn-outline-light" for="btn-check-battery">
                            <i class="fa fa-battery-half" title="See Battery Plot"></i> Battery
                        </label>
                        <input type="checkbox" class="btn-check" id="btn-check-msg" name="communication" value="1">
                        <label class="nav-link btn btn-outline-light" for="btn-check-msg">
                            <i class="fa fa-comment" title="See Communication Plot"></i> Communication
                        </label>
                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-outline-light btn-nav">Apply</button>
                        </div>

                    </div>
                </form>
                <div class="mt-auto">
                    <hr class="border-light">
                    <p class="navbar-brand text-center">Handle Log</p>
                    <div class="nav flex-column text-center">
                        <a href="{{ url_for('discovery.init') }}">
                            <button class="btn btn-outline-light btn-nav">
                                <i class="fa fa-arrow-left" title="Go Back to Discovery"></i> Back to Discovery
                            </button>
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>


    <div class="content">
        <div class="container-fluid">
            <!-- Process Area -->
            <div class="plot-card card">
                <div class="card-header">
                    <span class="collapse-toggle" data-bs-toggle="collapse" data-bs-target="#control_flow">
                        <i class="fa fa-spinner"></i> Control-flow Perspective
                    </span>
                </div>
                <div id="control_flow" class="collapse show card-body">
                    <div class="d-flex justify-content-end mb-3">
                        <div class="btn-group">
                            <button id="toggle-button" class="btn btn-outline-secondary"
                                title="Change Graph Direction"><i class="bi bi-arrow-repeat" aria-hidden="true"></i>
                            </button>
                            <button onclick="downloadGraph()" class="btn btn-outline-secondary" title="Download SVG"><i
                                    class="bi bi-download" aria-hidden="true"></i>
                            </button>
                        </div>
                    </div>
                    <div id="graph-container" style="height: 300px;"></div>
                </div>
            </div>

        </div>


        <!-- Plots Area -->
        <div class="container-fluid mt-3">
            <div class="row">
                {% if session.measures %}
                {% set activity_plots = session.measures.get(session.current_activity, session.measures['global'])
                %}

                <!-- Space Plot -->
                {% if activity_plots.space %}
                <div class="col-md-6">
                    <div class="plot-card card">
                        <div class="card-header">
                            <span class="collapse-toggle" data-bs-toggle="collapse" data-bs-target="#space_div">
                                <i class="fa fa-map"></i> Space Perspective
                            </span>
                        </div>
                        <div id="space_div" class="collapse show card-body">
                            {% for plot in activity_plots.space %}
                            {% include plot %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endif %}

                <!-- Time Plot -->
                {% if activity_plots.time %}
                <div class="col-md-6">
                    <div class="plot-card card">
                        <div class="card-header">
                            <span class="collapse-toggle" data-bs-toggle="collapse" data-bs-target="#time_div">
                                <i class="fa fa-calendar"></i> Time Perspective
                            </span>
                        </div>
                        <div id="time_div" class="collapse show card-body">
                            {% for plot in activity_plots.time %}
                            {% include plot %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endif %}

                <!-- Battery Plot -->
                {% if activity_plots.battery %}
                <div class="col-md-6">
                    <div class="plot-card card">
                        <div class="card-header">
                            <span class="collapse-toggle" data-bs-toggle="collapse" data-bs-target="#battery_div">
                                <i class="fa fa-battery-half"></i> Battery Perspective
                            </span>
                        </div>
                        <div id="battery_div" class="collapse show card-body">
                            {% for plot in activity_plots.battery %}
                            {% include plot %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endif %}

                <!-- Communication Plot -->
                {% if activity_plots.communication %}
                <div class="col-md-6">
                    <div class="plot-card card">
                        <div class="card-header">
                            <span class="collapse-toggle" data-bs-toggle="collapse" data-bs-target="#communication_div">
                                <i class="fa fa-comment"></i> Communication Perspective
                            </span>
                        </div>
                        <div id="communication_div" class="collapse show card-body">
                            {% for plot in activity_plots.communication %}
                            {% include plot %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endif %}


                {% else %}
                <p>No measures data available to display.</p>
                {% endif %}
            </div>
        </div>
    </div>

    <script>
        const response_data = {{ session.response_data|default ("") | tojson }};
        generate_dagre(response_data);
    </script>
</body>
{% endblock %}

</html>

templates/error_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 Error - Page Not Found</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .error-container {
            text-align: center;
        }

        .error-container h1 {
            font-size: 5em;
            margin-bottom: 0.5em;
            color: #5001b8;
        }

        .error-container p {
            font-size: 1.2em;
            margin-top: 0;
            color: #666;
        }

        .error-container a {
            text-decoration: none;
            color: #5001b8;
            font-weight: bold;
        }

        .error-container a:hover {
            text-decoration: underline;
        }

        .error-container img {
            max-width: 100%;
            height: auto;
        }
    </style>
</head>
<body>
    <div class="error-container">
        <h1>404</h1>
        <p>Oops! The page you're looking for cannot be found.</p>
        <p>Return to <a href="/">home page</a>.</p>
    </div>
</body>
</html>